### PR TITLE
Add new aliases

### PR DESCRIPTION
**Pull request by zommerfelds**
How about some useful aliases like `git commit`, `git push` and `git pull`, since they are used very frequently? These are the same as in scm_breeze.
Or would you say that it is the responsibility of the user to define custom aliases?

### CODE REVIEW

**Comment by mroth** [comment]
Hi @zommerfelds -- I greatly appreciate the contribution. I'm not sure what I want to do with this one yet.  My goal is to avoid setting as many aliases as possible.  I think `push/pull` are outside of the scope of scmpuff, since they don't take filename arguments (and thus numeric substitution wouldn't do anything for them).  For `commit`, apparently it _can_ take a filename argument, but I've certainly never used it myself that way.

In any event, I want to think about this one a little more, so apologies for the delay.  I'm considering even removing the core `ga` aliases from a default init FWIW, since they are somewhat outside of the actual functionality that scmpuff provides (and will "just work" if a user adds them theirselves).

**Comment by zommerfelds** [comment]
That makes sense. I just though you might want to provide a common set of aliases. My vote goes for either getting rid of all of them, or adding these ones since you are adding aliases anyway.
Best regards.

**Comment by zommerfelds** [comment]
Not sure if we're worried of colliding with other aliases, but we could define a command line argument that conditionally enables/disables the aliases.

**Comment by mroth** [comment]
> Not sure if we're worried of colliding with other aliases, but we could define a command line argument that conditionally enables/disables the aliases.

This exists via `scmpuff init -s --aliases=false` etc.

**Comment by zommerfelds** [comment]
Ah cool, so in a way the aliases are not that bad, since you can disable them if you don't like them.
If you don't want to merge this, let's close the PR.

**Pull request closed without merging**
